INSERT into skills_category (name, sort_order) VALUES  ('Tools & Technologies', 0);
INSERT into skills_category (name, sort_order) VALUES  ('Currently Learning', 1);
-- Tech Skills (category_id = 1)
INSERT INTO skill (category_id, name, icon, sort_order) VALUES
                                                            (1, 'React', 'devicon:react', 0),
                                                            (1, 'C#', 'devicon:csharp', 1),
                                                            (1, 'Python', 'devicon:python', 2),
                                                            (1, 'Git', 'devicon:git', 3),
                                                            (1, 'Azure', 'devicon:azure', 4),
                                                            (1, 'Microsoft SQL', 'ph:file-sql', 5),
                                                            (1, 'TypeScript', 'devicon:typescript', 6),
                                                            (1, 'Java', 'devicon:java', 7),
                                                            (1, 'C++', 'devicon:cplusplus', 8),
                                                            (1, 'Rust', 'devicon:rust', 9),
                                                            (1, 'PostgreSQL', 'devicon:postgresql', 10),
                                                            (1, 'Redux', 'devicon:redux', 11),
                                                            (1, 'Docker', 'devicon:docker', 12),
                                                            (1, 'Angular', 'devicon:angular', 13),
                                                            (1, 'TailwindCSS', 'devicon:tailwindcss', 14),
                                                            (1, 'Svelte', 'devicon:svelte', 15),
                                                            (1, 'Vue', 'devicon:vuejs', 16),
                                                            (1, 'Unity', 'devicon:unity', 17);

-- Learning Skills (category_id = 2)
INSERT INTO skill (category_id, name, icon, sort_order) VALUES
                                                            (2, 'Computer Architecture', 'icon-park-outline:chip', 0),
                                                            (2, 'SystemVerilog', 'vscode-icons:file-type-systemverilog', 1),
                                                            (2, 'RISC-V Assembly', 'file-icons:assembly-riscv', 2),
                                                            (2, 'QEMU', 'simple-icons:qemu', 3),
                                                            (2, 'VHDL', 'file-icons:vhdl', 4);

INSERT  INTO publications (slug, title, conference, year, pdf, url, doi, abstract, sort_order, authors) VALUES
                                                                                                            ('bridge-health', 'Bridge Health-Informed Route Planning: Challenges and Promises',
                                                                                                             'International Conference on Transportation and Development', 2024, 'pdfs/publications/Bridge Health-Informed Route Planning: Challenges and Promises.pdf', NULL, 'https://doi.org/10.1061/9780784485514.010', 'Ensuring bridge safety is crucial for transportation in many countries, including the US. In fact, the ASCE gave an overall cumulative grade of C− for US infrastructure, in large part due to deteriorating bridges. Unsafe bridges within transportation routes pose significant challenges to stakeholders including traffic safety concerns, environmental hazards, and economic implications. The collapse of Minneapolis I-35W bridge highlights these issues. Our research encourages stakeholders to make informed decisions by taking into account bridge risk factors and the sensitivity of transported materials (e.g., hazardous materials, heavy equipment). This approach enables strategies like load balancing, rerouting enforcement, and prioritizing maintenance tasks to be applied effectively. We generated a bridge-health enriched geographic information system (GIS) dataset that integrates bridge information from the National Bridge Inventory (NBI) with GIS data from OpenStreetMap. We analyzed example origin-destination (O-D) pairs in Nebraska to demonstrate how different routes in Nebraska exhibit, besides differences in travel distance, varying statistics on bridge health scores. We also introduce a simulation platform for route planning and visualization currently in active development. We finally discuss the challenges we faced and opportunities ahead in combining these distinct datasets for sustainable route planning and infrastructure maintenance.', 0,
                                                                                                             'Kassa, Y., Heller, W., Lacy, B., Ricks, B., Gandhi, R.'),
                                                                                                            ('vr-hand-dexerity', 'Use of Virtual Reality for Assessing Gross Hand Dexterity in Young Healthy Individuals', 'Summer Biomechanics, Bioengineering, and Biotransport Conference (SB³C). Vail, Colorado.', 2020, 'pdfs/publications/Use of Virtual Reality for Assessing Gross Hand Dexterity in Young Healthy Individuals.pdf', 'https://www.researchgate.net/publication/352741111_Use_of_Virtual_Reality_for_Assessing_Gross_Hand_Dexterity_in_Young_Healthy_Individuals_Extended_Abstract', NULL, 'Functional tasks, such as reaching and grasping, are an important aspect to quality of life that can be greatly impacted when motor deficits occur. Stroke is a leading cause of adult disability with approximately two-thirds of stroke survivors experiencing motor deficits. Early post-stroke neuro-rehabilitation can improve functional outcomes as indicated by improved Fugl-Myer Assessment scores. However, transportation and access to rehabilitation clinics can be a limiting factor for individuals in early post-stroke rehabilitation. Previous literature has studied the effects of Virtual Reality (VR) as a neuro-rehabilitation tool for stroke survivors and has reported increases in functional task performances. However, it is still not known whether VR systems provide the same level of care as conventional manual therapy. Many conventional rehabilitation protocols include a focus on improving gross hand dexterity. We can measure rehabilitation improvements in different domains through the use of Box and Blocks test and Functional Near Infrared Spectroscopy (fNIRS). The Box and Block test is a common measure of gross hand dexterity. In this test a participant is asked to move as many one-inch blocks as possible over a partition in a one-minute time limit. Improvements in functional tasks can also be assessed through brain imaging techniques such as fNIRS. fNIRS measures the changes in cortical blood oxygenation by detecting differences in the absorption of near-infrared light between oxygenated and deoxygenated blood. fNIRS has emerged as a practical neuroimaging technique to assess hemodynamic cortical responses and cortical reorganization. By delivering near-infrared lights via fiber optic cables, fNIRS is less sensitive to noise and movement artifacts than resonance imaging (fMRI) and electroencephalography (EEG). This makes fNIRS, easier for individuals to tolerate and providing excellent spatial resolution. The purpose of this pilot study is to assess the use of VR as a modality for testing gross hand dexterity in young healthy individuals while performing the Box and Block test under observation with fNIRS. We hypothesize that there will be no difference in the magnitude of brain activation between the manual and VR conditions of the Box and Block test for both the dominant and non-dominant hands.',1,
                                                                                                             'Parker, S., Leutzinger, T., Lacy, B., Ricks, B., Zuniga, J., Knarr, B.')
